language: python
env:
  - DJANGO="Django>=1.8.0,<1.9.0"
  - DJANGO="Django>=1.9.0,<1.10.0"
  - DJANGO=https://github.com/django/django/archive/stable/1.10.x.zip
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install --upgrade pip setuptools
  - pip install $DJANGO
  - pip install .
  - pip install coveralls
  - pip install coverage
script:
  - coverage run --source mezzanine setup.py test
notifications:
  irc: "irc.freenode.org#mezzanine"
  on_success: change
  on_failure: change
after_success: coveralls
